# Generated by Django 4.2.6 on 2023-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=150)),
                ('instrument', models.CharField(choices=[('piano', 'piano'), ('guitar', 'guitar')], max_length=150)),
                ('marks_avg', models.DecimalField(decimal_places=1, default=6.0, max_digits=3)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
